_NONE_ = "None"
__DEFAULT__ = "default"
__ALL__ = "all"

__PRIVATE__ = 0
__OWNER__ = 0
__VIEWER__ = 1
__COLLABORATOR__ = 2
__PUBLIC__ = 3

__INVENTORY__ = 1
__LIST__ = 2
__LIST_ALL__ = 3
__URL_LIST__ = 4

_MOVE_ = 0
_COPY_ = 1
_LINK_ = 2

__READ_ONLY__ = 2

__OK__ = 200
__BAD_REQUEST__ = 400
__UNAUTHORIZED__ = 401
__FORBIDDEN__ = 403
__NOT_FOUND__ = 404
__METHOD_NOT_ALLOWED__ = 405
__CONFLICT__ = 409
__GONE__ = 410
__INTERNAL_SERVER_ERROR__ = 500
__NOT_IMPLEMENTED__ = 501
__SERVICE_UNAVAILABLE__ = 503

__ERROR__ = "error"